In [2]:
import numpy as np

# Concatenate 

# Example - 1 (1D Array) 

In [159]:
c1 = np.arange(1,5)
c2 = np.arange(1,5)
print(c1)
print(c2)
print(c1.shape)
print(c2.shape)
print(c1.ndim)
print(c2.ndim)

[1 2 3 4]
[1 2 3 4]
(4,)
(4,)
1
1


In [160]:
# Now Concatinating the two arrays c1 and c2.

In [161]:
np.concatenate([c1,c2])

array([1, 2, 3, 4, 1, 2, 3, 4])

In [162]:
np.concatenate([c1,c2] , axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

#  In the above as we are performing the concatenation on the 1D arrays, giving axis "1"gives an error for the 1D array. But giving axis "0" works as they are the 1D arrays and "0" axis is the first dimension. 

In [163]:
np.concatenate([c1,c2] , axis = 0)

array([1, 2, 3, 4, 1, 2, 3, 4])

#  Example - 2 (2D Array)

In [164]:
c1 = np.arange(12).reshape(4,3)
c2 = np.arange(12).reshape(4,3)

In [165]:
print(c1)
print(c2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [166]:
print(c1.shape)
print(c1.ndim)

(4, 3)
2


In [167]:
print(c2.shape)
print(c2.ndim)

(4, 3)
2


# Concatenating Normally without axis

In [168]:
c3 = np.concatenate([c1,c2])

In [169]:
c3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [170]:
print(c3.shape)
print(c3.ndim)

(8, 3)
2


# Concatenating with respect to axis=1

In [171]:
c4 = np.concatenate([c1,c2] , axis = 1)

In [172]:
c4

array([[ 0,  1,  2,  0,  1,  2],
       [ 3,  4,  5,  3,  4,  5],
       [ 6,  7,  8,  6,  7,  8],
       [ 9, 10, 11,  9, 10, 11]])

In [173]:
print(c4.shape)
print(c4.ndim)

(4, 6)
2


# Concatenating with respect to axis=0

In [174]:
c5 = np.concatenate([c1,c2] , axis = 0)

In [175]:
c5

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [176]:
print(c5.shape)
print(c5.ndim)

(8, 3)
2


# Note - For concatenating the default axis is equal to zero.

# Example - 3 (Taking 2D arrays of different shapes)

In [177]:
c1 = np.arange(1,5).reshape(1,4)
c2 = np.arange(12).reshape(3,4)

In [178]:
print(c1)
print(c1.shape)
print(c1.ndim)

[[1 2 3 4]]
(1, 4)
2


In [179]:
print(c2)
print(c2.shape)
print(c2.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [180]:
c3 = np.concatenate([c1,c2])

In [181]:
print(c3)
print(c3.shape)
print(c3.ndim)

[[ 1  2  3  4]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(4, 4)
2


In [182]:
c4 = np.concatenate([c1,c2] , axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 3

In [183]:
c5 = np.concatenate([c2,c1])
c5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  4]])

# Example - 4 (Taking one 1D array and one 2D array)

In [184]:
c1 = np.arange(12).reshape(3,4)
c2 = np.arange(1,5)

In [185]:
print(c1)
print(c1.shape)
print(c1.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [186]:
print(c2)
print(c2.shape)
print(c2.ndim)

[1 2 3 4]
(4,)
1


In [187]:
np.concatenate([c1,c2])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [188]:
np.concatenate([c1,c2] , axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [189]:
np.concatenate([c1,c2] , axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# Stacking 

In [190]:
# Example-1 (Two 1D arrays)

In [191]:
c1 = np.arange(1,5)
c2 = np.arange(1,5)
print(c1)
print(c2)
print(c1.shape)
print(c2.shape)
print(c1.ndim)
print(c2.ndim)

[1 2 3 4]
[1 2 3 4]
(4,)
(4,)
1
1


# Applying "hstack".

In [192]:
c3 = np.hstack([c1,c2])
c3

array([1, 2, 3, 4, 1, 2, 3, 4])

In [193]:
print(c3.shape)
print(c3.ndim)

(8,)
1


# Applying vstack

In [194]:
c4 = np.vstack([c1,c2])
c4

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [195]:
print(c4.shape)
print(c4.ndim)

(2, 4)
2


# Example - 2 (2D Array)

In [196]:
c1 = np.arange(12).reshape(4,3)
c2 = np.arange(12).reshape(4,3)

In [197]:
print(c1)
print(c2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [198]:
print(c1.shape)
print(c1.ndim)

(4, 3)
2


In [199]:
print(c2.shape)
print(c2.ndim)

(4, 3)
2


In [200]:
c3 = np.hstack([c1,c2])
print(c3)
print(c3.shape)
print(c3.ndim)

[[ 0  1  2  0  1  2]
 [ 3  4  5  3  4  5]
 [ 6  7  8  6  7  8]
 [ 9 10 11  9 10 11]]
(4, 6)
2


In [201]:
c4 = np.vstack([c1,c2])
print(c4.shape)
print(c4.ndim)

(8, 3)
2


# Example - 3 (Taking 2D arrays of different shapes)

In [202]:
c1 = np.arange(1,5).reshape(1,4)
c2 = np.arange(12).reshape(3,4)

In [203]:
print(c1)
print(c1.shape)
print(c1.ndim)

[[1 2 3 4]]
(1, 4)
2


In [204]:
print(c2)
print(c2.shape)
print(c2.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [205]:
np.hstack([c1,c2])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 3

In [206]:
np.vstack([c1,c2])

array([[ 1,  2,  3,  4],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Example - 4 (Taking one 1D array and one 2D array)

In [207]:
c1 = np.arange(12).reshape(3,4)
c2 = np.arange(1,5)

In [208]:
print(c1)
print(c1.shape)
print(c1.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [209]:
print(c2)
print(c2.shape)
print(c2.ndim)

[1 2 3 4]
(4,)
1


In [210]:
np.hstack([c1,c2])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [211]:
np.vstack([c1,c2])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  4]])

# Splitting 

In [357]:
c_1 = np.arange(1,13)
print(c_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Splitting array in to 3 equal parts.

In [358]:
np.split(c_1,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

# Splitting array in to 4 equal parts.

In [359]:
np.split(c_1,4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

# Splitting array in to 2 equal parts.

In [360]:
np.split(c_1,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

# Splitting array in to 6 equal parts.

In [361]:
np.split(c_1,6)

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12])]

# Splitting array in to 5 equal parts 

In [362]:
np.split(c_1,5)

ValueError: array split does not result in an equal division

# Splitting based on indices.

In [363]:
np.split(c_1,[5]) # Here "5" is the index.

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11, 12])]

In [364]:
np.split(c_1,[5,7])

[array([1, 2, 3, 4, 5]), array([6, 7]), array([ 8,  9, 10, 11, 12])]

In [365]:
np.split(c_1,[5,6])

[array([1, 2, 3, 4, 5]), array([6]), array([ 7,  8,  9, 10, 11, 12])]

In [366]:
np.split(c_1 , [5,7,10])

[array([1, 2, 3, 4, 5]), array([6, 7]), array([ 8,  9, 10]), array([11, 12])]

In [367]:
np.split(c_1 , [0,5,12])

[array([], dtype=int32),
 array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11, 12]),
 array([], dtype=int32)]

In [368]:
c_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [369]:
np.split(c_1 , [2,10,6])

[array([1, 2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10]),
 array([], dtype=int32),
 array([ 7,  8,  9, 10, 11, 12])]

In [375]:
c_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [370]:
np.split(c_1,[-5])

[array([1, 2, 3, 4, 5, 6, 7]), array([ 8,  9, 10, 11, 12])]

In [371]:
np.split(c_1 , [-5,-3])

[array([1, 2, 3, 4, 5, 6, 7]), array([8, 9]), array([10, 11, 12])]

In [372]:
np.split(c_1 , [-5,-9])

[array([1, 2, 3, 4, 5, 6, 7]),
 array([], dtype=int32),
 array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])]

In [376]:
c_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [378]:
np.split(c_1,[2,10,6])

[array([1, 2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10]),
 array([], dtype=int32),
 array([ 7,  8,  9, 10, 11, 12])]

In [379]:
np.split(c_1 , [5,2,13])

[array([1, 2, 3, 4, 5]),
 array([], dtype=int32),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([], dtype=int32)]

# Splitting 2D arrays

In [373]:
c_2 = np.arange(1,13).reshape(4,3)

In [374]:
c_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [332]:
np.split(c_2,4,axis=0)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

In [380]:
np.vsplit(c_2,4)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

# Note - We can also use vsplit to do the same operation when You do not want to use the axis. 

In [382]:
c_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [333]:
np.split(c_2,3,axis = 1)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [384]:
np.hsplit(c_2,3)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

# Note - In the sae way hsplit can we used when we want to split the array horizontally without using the axis.

# Split the array in to two equal parts vertically.

In [334]:
np.split(c_2,2,axis=0)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [385]:
np.vsplit(c_2,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

# Split the array in to three horizontal parts equally.

In [386]:
c_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [336]:
np.split(c_2,3,axis= 1)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [387]:
np.hsplit(c_2,3)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [337]:
c_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Using hsplit (Using horizontal split)

In [338]:
np.hsplit(c_2,3)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

# Using vsplit (Vertical split)

In [339]:
np.vsplit(c_2,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

# Splitting with indices  

In [340]:
c_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [341]:
np.split(c_2, [1] , axis = 0)

[array([[1, 2, 3]]),
 array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])]

# Split the first two rows and the last two rows of c1

In [342]:
np.split(c_2 , [0,2] , axis = 0)

[array([], shape=(0, 3), dtype=int32),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

# Split the first three rows and last row of c1.

In [343]:
c_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [344]:
np.split(c_2 , [0,3] , axis = 0)

[array([], shape=(0, 3), dtype=int32),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12]])]

# Split the first two columns and last column.

In [345]:
c_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [346]:
np.split(c_2 , [0,2] , axis = 1)

[array([], shape=(4, 0), dtype=int32),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

# Split the first column and the last two columns 

In [347]:
np.split(c_2 , [0,1] , axis = 1)

[array([], shape=(4, 0), dtype=int32),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2,  3],
        [ 5,  6],
        [ 8,  9],
        [11, 12]])]

# Instead of giving the axis, hsplit and vsplit can be used.

In [348]:
c_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Split the first two columns and last column of c1 using hsplit.

In [349]:
np.hsplit(c_2 , [0,2])

[array([], shape=(4, 0), dtype=int32),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

# Split the first column and next two columns of c1 using hsplit.

In [350]:
np.hsplit(c_2 , [0,1])

[array([], shape=(4, 0), dtype=int32),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2,  3],
        [ 5,  6],
        [ 8,  9],
        [11, 12]])]

# Split the three columns of c1 equally using hsplit.

In [351]:
np.hsplit(c_2,[0,1,2])

[array([], shape=(4, 0), dtype=int32),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

# Split the first row and next three rows of c1 using vsplit.

In [352]:
c_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [353]:
np.vsplit(c_2 , [0,1])

[array([], shape=(0, 3), dtype=int32),
 array([[1, 2, 3]]),
 array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])]

# Split the first two rows and next two rows of c1 equally.

In [354]:
np.vsplit(c_2 , [0,2])

[array([], shape=(0, 3), dtype=int32),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

# Split each row of the c1 array equally.

In [355]:
np.split(c_2 , [0,1,2,3])

[array([], shape=(0, 3), dtype=int32),
 array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

# Broadcasting.

# Rules of Broadcasting. (Going from Right side).


# 1 . The dimensions for both matrices should be equal, then

# 2. The size of atleast one dimension should be 1.

# Rule1 : If two arrays differ in number of dimensions, the shape of one with fewer dimensions is padded with ones on its leading side (left side).

# Rule :2 If the shape of two arrays does not match in any dimensions, the array with shape equal to 1 is stretched to match the other shape.

# 4. If in any dimension the shapes disagree and neither equal to 1, then error is raised.

In [3]:
A = np.arange(1,5)
A+2

array([3, 4, 5, 6])

In [253]:
B = np.arange(1,7).reshape(3,2)
print(B)
print(B.shape)
print(B.ndim)
C = np.arange(1,3)
print(C)
print(C.shape)
print(C.ndim)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2
[1 2]
(2,)
1


In [254]:
B+C

array([[2, 4],
       [4, 6],
       [6, 8]])

In [255]:
D =np.arange(1,4)
D

array([1, 2, 3])

In [256]:
B + D

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [257]:
A = np.arange(1,7).reshape(3,2)
print(A)
print(A.shape)
print(A.ndim)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2


In [258]:
B = np.array([10,20,30,40]).reshape(2,2)
print(B)
print(B.shape)
print(B.ndim)

[[10 20]
 [30 40]]
(2, 2)
2


In [259]:
A+B

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [260]:
A = np.array([[1,2,3]])
print(A)
print(A.shape)
print(A.ndim)

[[1 2 3]]
(1, 3)
2


In [261]:
B = np.array([[10],[20],[30]])
print(B)
print(B.shape)
print(B.ndim)

[[10]
 [20]
 [30]]
(3, 1)
2


In [262]:
A + B

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [263]:
A = np.arange(1,5).reshape(1,4)
print(A)
print(A.shape)
print(A.ndim)

[[1 2 3 4]]
(1, 4)
2


In [264]:
B = np.arange(1,6).reshape(5,1)
print(B)
print(B.shape)
print(B.ndim)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)
2


In [265]:
A + B

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

# Assignments.

In [266]:
arr1 = np.array([1,2,3,6,3,2]) 

arr2 = np.array([4,2,1,3,3,2]) 

arr3 = np.zeros(len(arr1)) 

In [267]:
arr1

array([1, 2, 3, 6, 3, 2])

In [268]:
arr2

array([4, 2, 1, 3, 3, 2])

In [269]:
arr3

array([0., 0., 0., 0., 0., 0.])

In [270]:
for i in range(len(arr1)): 

    arr3[i] = arr1[i] * arr2[i]

In [271]:
arr3

array([ 4.,  4.,  3., 18.,  9.,  4.])

In [272]:
arr3 = arr1*arr2 

In [273]:
arr3

array([ 4,  4,  3, 18,  9,  4])

In [274]:

for i in range(len(arr1)): 

    if(arr1[i] < 0 ): 

        arr1[i] = -1 

    else: 

        arr1[i] = 1

In [275]:
arr1

array([1, 1, 1, 1, 1, 1])

In [276]:
np.where(arr1 > 0, 1, -1) 

array([1, 1, 1, 1, 1, 1])

In [277]:
arr = np.arange(16).reshape(4,4)

print(np.split(arr, 4))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [278]:
A.shape = (4,)

B.shape = (3, 1)

C.shape = (3 , 4)

ValueError: cannot reshape array of size 5 into shape (3,1)

In [279]:
A = np.array([1,2,3,4])

In [280]:
A.shape

(4,)

In [281]:
B = np.array([1,2,3]).reshape(3,1)

In [282]:
B

array([[1],
       [2],
       [3]])

In [283]:
B.shape

(3, 1)

In [284]:
C = np.arange(12).reshape(3,4)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [285]:
np.concatenate((C, B), axis = 0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 1

In [286]:
np.concatenate((C, A), axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [287]:
np.concatenate((C.T, A.reshape(4,1)), axis = 1)

array([[ 0,  4,  8,  1],
       [ 1,  5,  9,  2],
       [ 2,  6, 10,  3],
       [ 3,  7, 11,  4]])

In [288]:
np.concatenate((A,B), axis=0)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [289]:
mat = np.array([1,2,3,4,5,6]).reshape(3,2)

In [290]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [291]:
mat.shape

(3, 2)

In [292]:
mat.shape[0]

3

In [293]:
mat.shape[1]

2

In [294]:
n = len(mat)

In [295]:
n 

3

In [296]:
m = len(mat[1])

In [297]:
m

2

In [298]:
intmdt_mat1 = np.vstack((mat,[0]*m))

In [299]:
intmdt_mat1

array([[1, 2],
       [3, 4],
       [5, 6],
       [0, 0]])

In [300]:
intmdt_mat2 = np.vstack(([0]*m,intmdt_mat1))

In [301]:
intmdt_mat2

array([[0, 0],
       [1, 2],
       [3, 4],
       [5, 6],
       [0, 0]])

In [302]:
 #a = np.array([0]*(n+2)).reshape(n+2,1)
a = np.array([0] * (m+2)).reshape(n+2 , 1)


ValueError: cannot reshape array of size 4 into shape (5,1)

In [303]:
a

NameError: name 'a' is not defined

In [304]:
intmdt_mat3 = np.hstack((intmdt_mat2, a))

NameError: name 'a' is not defined

In [305]:
intmdt_mat3

NameError: name 'intmdt_mat3' is not defined

In [306]:
res = np.hstack((a, intmdt_mat3))

NameError: name 'a' is not defined

In [307]:
res

NameError: name 'res' is not defined

In [308]:
m = mat[0] # Number of rows.
n = mat[1] # Number of columns.
arr1 = np.vstack(mat , [0] * n)
arr2 = np.vstack([0] * n , arr1)
arr3 = np.array(mat[0] +2).reshape(m+2 , 1)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [4]:
A = np.arange(1,9).reshape(2,4)

In [5]:
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
B = np.arange(1,7).reshape(1,6)

In [7]:
B

array([[1, 2, 3, 4, 5, 6]])

In [8]:
A+B

ValueError: operands could not be broadcast together with shapes (2,4) (1,6) 

In [10]:
A = np.arange(1,7).reshape(2,3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
B = np.array([10,20])

In [12]:
A + B

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [13]:
A = np.arange(1,9).reshape(2,4)
B = np.arange(1,5).reshape(1,4)

In [14]:
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
B

array([[1, 2, 3, 4]])

In [16]:
A + B

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [45]:
arr_1 = np.arange(1,21).reshape(4,5) 

In [46]:
arr_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [47]:
arr_2 = np.arange(1,7).reshape(6,1)

In [48]:
arr_2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [49]:
arr_1 + arr_2

ValueError: operands could not be broadcast together with shapes (4,5) (6,1) 