In [303]:
import numpy as np

# Concatenate 

# Example - 1 (1D Array) 

In [304]:
c1 = np.arange(1,5)
c2 = np.arange(1,5)
print(c1)
print(c2)
print(c1.shape)
print(c2.shape)
print(c1.ndim)
print(c2.ndim)

[1 2 3 4]
[1 2 3 4]
(4,)
(4,)
1
1


In [305]:
# Now Concatinating the two arrays c1 and c2.

In [306]:
np.concatenate([c1,c2])

array([1, 2, 3, 4, 1, 2, 3, 4])

In [307]:
np.concatenate([c1,c2] , axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

#  In the above as we are performing the concatenation on the 1D arrays, giving axis "1"gives an error for the 1D array. But giving axis "0" works as they are the 1D arrays and "0" axis is the first dimension. 

In [308]:
np.concatenate([c1,c2] , axis = 0)

array([1, 2, 3, 4, 1, 2, 3, 4])

#  Example - 2 (2D Array)

In [309]:
c1 = np.arange(12).reshape(4,3)
c2 = np.arange(12).reshape(4,3)

In [310]:
print(c1)
print(c2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [311]:
print(c1.shape)
print(c1.ndim)

(4, 3)
2


In [312]:
print(c2.shape)
print(c2.ndim)

(4, 3)
2


# Concatenating Normally without axis

In [313]:
c3 = np.concatenate([c1,c2])

In [314]:
c3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [315]:
print(c3.shape)
print(c3.ndim)

(8, 3)
2


# Concatenating with respect to axis=1

In [316]:
c4 = np.concatenate([c1,c2] , axis = 1)

In [317]:
c4

array([[ 0,  1,  2,  0,  1,  2],
       [ 3,  4,  5,  3,  4,  5],
       [ 6,  7,  8,  6,  7,  8],
       [ 9, 10, 11,  9, 10, 11]])

In [318]:
print(c4.shape)
print(c4.ndim)

(4, 6)
2


# Concatenating with respect to axis=0

In [319]:
c5 = np.concatenate([c1,c2] , axis = 0)

In [320]:
c5

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [321]:
print(c5.shape)
print(c5.ndim)

(8, 3)
2


# Note - For concatenating the default axis is equal to zero.

# Example - 3 (Taking 2D arrays of different shapes)

In [322]:
c1 = np.arange(1,5).reshape(1,4)
c2 = np.arange(12).reshape(3,4)

In [323]:
print(c1)
print(c1.shape)
print(c1.ndim)

[[1 2 3 4]]
(1, 4)
2


In [324]:
print(c2)
print(c2.shape)
print(c2.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [325]:
c3 = np.concatenate([c1,c2])

In [326]:
print(c3)
print(c3.shape)
print(c3.ndim)

[[ 1  2  3  4]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(4, 4)
2


In [327]:
c4 = np.concatenate([c1,c2] , axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 3

In [328]:
c5 = np.concatenate([c2,c1])
    c5

IndentationError: unexpected indent (Temp/ipykernel_27724/2803149120.py, line 2)

# Example - 4 (Taking one 1D array and one 2D array)

In [329]:
c1 = np.arange(12).reshape(3,4)
c2 = np.arange(1,5)

In [330]:
print(c1)
print(c1.shape)
print(c1.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [331]:
print(c2)
print(c2.shape)
print(c2.ndim)

[1 2 3 4]
(4,)
1


In [332]:
np.concatenate([c1,c2])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [333]:
np.concatenate([c1,c2] , axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [334]:
np.concatenate([c1,c2] , axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# Stacking 

In [335]:
# Example-1 (Two 1D arrays)

In [336]:
c1 = np.arange(1,5)
c2 = np.arange(1,5)
print(c1)
print(c2)
print(c1.shape)
print(c2.shape)
print(c1.ndim)
print(c2.ndim)

[1 2 3 4]
[1 2 3 4]
(4,)
(4,)
1
1


# Applying "hstack".

In [337]:
c3 = np.hstack([c1,c2])
c3

array([1, 2, 3, 4, 1, 2, 3, 4])

In [338]:
print(c3.shape)
print(c3.ndim)

(8,)
1


# Applying vstack

In [339]:
c4 = np.vstack([c1,c2])
c4

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [340]:
print(c4.shape)
print(c4.ndim)

(2, 4)
2


# Example - 2 (2D Array)

In [341]:
c1 = np.arange(12).reshape(4,3)
c2 = np.arange(12).reshape(4,3)

In [342]:
print(c1)
print(c2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [343]:
print(c1.shape)
print(c1.ndim)

(4, 3)
2


In [344]:
print(c2.shape)
print(c2.ndim)

(4, 3)
2


In [345]:
c3 = np.hstack([c1,c2])
print(c3)
print(c3.shape)
print(c3.ndim)

[[ 0  1  2  0  1  2]
 [ 3  4  5  3  4  5]
 [ 6  7  8  6  7  8]
 [ 9 10 11  9 10 11]]
(4, 6)
2


In [346]:
c4 = np.vstack([c1,c2])
print(c4.shape)
print(c4.ndim)

(8, 3)
2


# Example - 3 (Taking 2D arrays of different shapes)

In [347]:
c1 = np.arange(1,5).reshape(1,4)
c2 = np.arange(12).reshape(3,4)

In [348]:
print(c1)
print(c1.shape)
print(c1.ndim)

[[1 2 3 4]]
(1, 4)
2


In [349]:
print(c2)
print(c2.shape)
print(c2.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [350]:
np.hstack([c1,c2])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 3

In [351]:
np.vstack([c1,c2])

array([[ 1,  2,  3,  4],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Example - 4 (Taking one 1D array and one 2D array)

In [352]:
c1 = np.arange(12).reshape(3,4)
c2 = np.arange(1,5)

In [353]:
print(c1)
print(c1.shape)
print(c1.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [354]:
print(c2)
print(c2.shape)
print(c2.ndim)

[1 2 3 4]
(4,)
1


In [355]:
np.hstack([c1,c2])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [356]:
np.vstack([c1,c2])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  4]])

# Splitting 

In [357]:
c1 = np.arange(1,13)
print(c1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Splitting array in to 3 equal parts.

In [358]:
np.split(c1,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

# Splitting array in to 4 equal parts.

In [359]:
np.split(c1,4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

# Splitting array in to 2 equal parts.

In [360]:
np.split(c1,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

# Splitting array in to 6 equal parts.

In [361]:
np.split(c1,6)

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12])]

# Splitting array in to 5 equal parts 

In [362]:
np.split(c1,5)

ValueError: array split does not result in an equal division

# Splitting based on indices.

In [363]:
np.split(c1,[5]) # Here "5" is the index.

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11, 12])]

In [364]:
np.split(c1,[5,7])

[array([1, 2, 3, 4, 5]), array([6, 7]), array([ 8,  9, 10, 11, 12])]

In [365]:
np.split(c1,[5,6])

[array([1, 2, 3, 4, 5]), array([6]), array([ 7,  8,  9, 10, 11, 12])]

In [366]:
np.split(c1 , [5,7,10])

[array([1, 2, 3, 4, 5]), array([6, 7]), array([ 8,  9, 10]), array([11, 12])]

In [367]:
np.split(c1 , [0,5,12])

[array([], dtype=int32),
 array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11, 12]),
 array([], dtype=int32)]

In [368]:
np.split(c1 , [2,10,6])

[array([1, 2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10]),
 array([], dtype=int32),
 array([ 7,  8,  9, 10, 11, 12])]

In [369]:
np.split(c1 , [-5,-3])

[array([1, 2, 3, 4, 5, 6, 7]), array([8, 9]), array([10, 11, 12])]

In [370]:
np.split(c1 , [-5,-9])

[array([1, 2, 3, 4, 5, 6, 7]),
 array([], dtype=int32),
 array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])]

# Splitting 2D arrays

In [371]:
c1 = np.arange(1,13).reshape(4,3)

In [372]:
c1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [373]:
np.split(c1,4,axis=0)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

In [374]:
np.split(c1,3,axis = 1)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

# Split the array in to two equal parts vertically.

In [375]:
np.split(c1,2,axis=0)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [376]:
# Split the array in to three horizontal parts equally.

In [377]:
np.split(c1,3,axis= 1)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [378]:
c1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Using hsplit (Using horizontal split)

In [379]:
np.hsplit(c1,3)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

# Using vsplit (Vertical split)

In [380]:
np.vsplit(c1,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

# Splitting with indices  

In [381]:
c1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [382]:
np.split(c1, [1] , axis = 0)

[array([[1, 2, 3]]),
 array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])]

# Split the first two rows and the last two rows of c1

In [383]:
np.split(c1 , [0,2] , axis = 0)

[array([], shape=(0, 3), dtype=int32),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

# Split the first three rows and last row of c1.

In [384]:
c1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [385]:
np.split(c1 , [0,3] , axis = 0)

[array([], shape=(0, 3), dtype=int32),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12]])]

# Split the first two columns and last column.

In [386]:
np.split(c1 , [0,2] , axis = 1)

[array([], shape=(4, 0), dtype=int32),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

# Split the first column and the last two columns 

In [387]:
np.split(c1 , [0,1] , axis = 1)

[array([], shape=(4, 0), dtype=int32),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2,  3],
        [ 5,  6],
        [ 8,  9],
        [11, 12]])]

# Instead of giving the axis, hsplit and vsplit can be used.

In [388]:
c1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Split the first two columns and last column of c1 using hsplit.

In [389]:
np.hsplit(c1 , [0,2])

[array([], shape=(4, 0), dtype=int32),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

# Split the first column and next two columns of c1 using hsplit.

In [390]:
np.hsplit(c1 , [0,1])

[array([], shape=(4, 0), dtype=int32),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2,  3],
        [ 5,  6],
        [ 8,  9],
        [11, 12]])]

# Split the three columns of c1 equally using hsplit.

In [391]:
np.hsplit(c1,[0,1,2])

[array([], shape=(4, 0), dtype=int32),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

# Split the first row and next three rows of c1 using vsplit.

In [392]:
c1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [393]:
np.vsplit(c1 , [0,1])

[array([], shape=(0, 3), dtype=int32),
 array([[1, 2, 3]]),
 array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])]

# Split the first two rows and next two rows of c1 equally.

In [394]:
np.vsplit(c1 , [0,2])

[array([], shape=(0, 3), dtype=int32),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

# Split each row of the c1 array equally.

In [395]:
np.split(c1 , [0,1,2,3])

[array([], shape=(0, 3), dtype=int32),
 array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

# Broadcasting.

In [397]:
A = np.arange(1,5)
A+2

array([3, 4, 5, 6])

In [404]:
B = np.arange(1,7).reshape(3,2)
print(B)
print(B.shape)
print(B.ndim)
C = np.arange(1,3)
print(C)
print(C.shape)
print(C.ndim)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2
[1 2]
(2,)
1


In [405]:
B+C

array([[2, 4],
       [4, 6],
       [6, 8]])

In [408]:
D =np.arange(1,4)
D

array([1, 2, 3])

In [409]:
B + D

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [411]:
A = np.arange(1,7).reshape(3,2)
print(A)
print(A.shape)
print(A.ndim)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2


In [417]:
B = np.array([10,20,30,40]).reshape(2,2)
print(B)
print(B.shape)
print(B.ndim)

[[10 20]
 [30 40]]
(2, 2)
2


In [418]:
A+B

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [419]:
A = np.array([[1,2,3]])
print(A)
print(A.shape)
print(A.ndim)

[[1 2 3]]
(1, 3)
2


In [420]:
B = np.array([[10],[20],[30]])
print(B)
print(B.shape)
print(B.ndim)

[[10]
 [20]
 [30]]
(3, 1)
2


In [422]:
A + B

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [425]:
A = np.arange(1,5).reshape(1,4)
print(A)
print(A.shape)
print(A.ndim)

[[1 2 3 4]]
(1, 4)
2


In [426]:
B = np.arange(1,6).reshape(5,1)
print(B)
print(B.shape)
print(B.ndim)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)
2


In [427]:
A + B

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])